### ISSUE TITLE
NoClassDefFoundError when trying to start the application

### ISSUE THREAD

**Issue by carminexx** [federecio/dropwizard-swagger#28]
Hi,
I'm trying to use dropwizard-swagger in a simple Dropwizard app; I followed the simple getting started tutorial; and I've added the dependency in my pom.xml; then I added the call to onInitialize in initialize() routine; and onRun in run().

Now, when I try to run the project, I get this error:

Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/jersey/spi/service/ServiceFinder
    at io.dropwizard.views.ViewBundle.<init>(ViewBundle.java:87)
    at io.federecio.dropwizard.swagger.SwaggerDropwizard.onInitialize(SwaggerDropwizard.java:40)

The problem seems to be on .onInitialize() call; in fact if I comment that out, the application starts, but obviously the /swagger endpoint doesn't work (500 error).

**Comment by alph486** [comment]
Hi @carminexx , which dependency were you missing? I have the same issue.

Thanks!

**Comment by artpar** [comment]
@carminexx yeah, detail please. i tried including jersey-core and dropwizard-freemarker-view, but both of  them did not solve it for me.

Thanks!

**Comment by alph486** [comment]
@artpar Try looking in #37 and #30 . Someone mentions the dependency but because the structure of the classes that have been changed I dont think its as simple as just excluding and/or including dependencies. There are changes that need to be made to make this work. Someone in #30 has submitted a PR for this.
